//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavisca.Content.ImageQuality.Model.Models.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FaultCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaultCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tavisca.Content.ImageQuality.Model.Models.Errors.FaultCodes", typeof(FaultCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 109.
        /// </summary>
        public static string BufferNullToCreateMemoryStream {
            get {
                return ResourceManager.GetString("BufferNullToCreateMemoryStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101.
        /// </summary>
        public static string DownloadFailure {
            get {
                return ResourceManager.GetString("DownloadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 204.
        /// </summary>
        public static string FileCreationFailure {
            get {
                return ResourceManager.GetString("FileCreationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 103.
        /// </summary>
        public static string FileInUseError {
            get {
                return ResourceManager.GetString("FileInUseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 518.
        /// </summary>
        public static string InvalidRequestHeaders {
            get {
                return ResourceManager.GetString("InvalidRequestHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 108.
        /// </summary>
        public static string IOErrorWhileReadingStream {
            get {
                return ResourceManager.GetString("IOErrorWhileReadingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101.
        /// </summary>
        public static string MissingField {
            get {
                return ResourceManager.GetString("MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 517.
        /// </summary>
        public static string MissingRequestHeaders {
            get {
                return ResourceManager.GetString("MissingRequestHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110.
        /// </summary>
        public static string NoBrisqueFeatures {
            get {
                return ResourceManager.GetString("NoBrisqueFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102.
        /// </summary>
        public static string NoUrl {
            get {
                return ResourceManager.GetString("NoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104.
        /// </summary>
        public static string NullOrEmptyImageUrl {
            get {
                return ResourceManager.GetString("NullOrEmptyImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 106.
        /// </summary>
        public static string OutOfMemoryWhileReadingStream {
            get {
                return ResourceManager.GetString("OutOfMemoryWhileReadingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        public static string QualityError {
            get {
                return ResourceManager.GetString("QualityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 107.
        /// </summary>
        public static string StreamReadingFailure {
            get {
                return ResourceManager.GetString("StreamReadingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 105.
        /// </summary>
        public static string UrlDownloadFailure {
            get {
                return ResourceManager.GetString("UrlDownloadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        public static string ValidationFailure {
            get {
                return ResourceManager.GetString("ValidationFailure", resourceCulture);
            }
        }
    }
}
